### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by muki** [danesjenovdan/parlameter#98]
Use https://github.com/kazupon/vue-i18n at compile time.

Import into devBundle.js and serverBundle.js.

Think about setting locale in card.json or even as an argument to build.

The messages JSON should be stored in the /i18n/.

When you create the Slovenian messages JSON (doesn't need to be done, it just need to exist in a defined form) ping @muki to configure [Crowdin](https://crowdin.com/project/parlanode/).

**Comment by LepkoQQ** [comment]
this is now done
